- .github/workflows/ci.yml
- mypy.ini
- pants-pytooling/pytooling_distribution/BUILD
- pants.toml
- pytest-patches/pytest_patches/__init__.py
> repo: Add pants typecheck

- .github/workflows/ci.yml
> repo: Re-enable publishing

- envoy.docker.utils/envoy/docker/utils/utils.py
ref: https://github.com/aio-libs/aiodocker/blob/9dcaf4785b0ee63b604380725282ab48ee5374f4/aiodocker/docker.py#L66
> fix: Use None as default docker url

- README.md
- deps/requirements.txt
- envoy.docs.sphinx_runner/envoy/docs/sphinx_runner/BUILD
- envoy.docs.sphinx_runner/setup.cfg
> Docs: Use pygments==2.10.0

- .gitignore
> gitignore: Add some ignores

- README.md
- deps/requirements.txt
- envoy.code_format.python_check/setup.cfg
- envoy.dependency.pip_check/setup.cfg
- envoy.distribution.distrotest/setup.cfg
- envoy.distribution.verify/setup.cfg
> repo: Bump dependency versions

- envoy.code_format.python_check/tests/test_abstract.py
> envoy.code_format.python_check: Fix test mock

- .github/workflows/ci.yml
- pants.toml
> repo: Update pants -> 2.9.0

- pants
> repo: Add pants script

- README.md
- envoy.dependency.check/envoy/dependency/check/BUILD
- envoy.dependency.check/envoy/dependency/check/__init__.py
- envoy.dependency.check/envoy/dependency/check/abstract/__init__.py
- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/envoy/dependency/check/abstract/dependency.py
- envoy.dependency.check/envoy/dependency/check/abstract/release.py
- envoy.dependency.check/envoy/dependency/check/abstracts.py
- envoy.dependency.check/envoy/dependency/check/checker.py
- envoy.dependency.check/setup.cfg
- envoy.dependency.check/tests/BUILD
- envoy.dependency.check/tests/test_abstract_checker.py
- envoy.dependency.check/tests/test_abstract_dependency.py
- envoy.dependency.check/tests/test_abstract_release.py
- envoy.dependency.check/tests/test_checker.py
> libs: Add `envoy.dependency.check[release-dates]`

- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/envoy/dependency/check/abstract/dependency.py
- envoy.dependency.check/tests/test_abstract_checker.py
- envoy.dependency.check/tests/test_abstract_dependency.py
> libs: Add `envoy.dependency.check[releases]`

- aio.core/aio/core/BUILD
- aio.core/aio/core/functional/__init__.py
- aio.core/aio/core/functional/collections.py
- aio.core/aio/core/functional/process.py
- aio.core/aio/core/functional/utils.py
- aio.core/tests/test_functional.py
- async_list
- async_set
- async_map
- maybe_coro
- maybe_awaitable
> aio.core: Add async functional functions

- aio.core/aio/core/BUILD
- aio.core/aio/core/functional/__init__.py
- aio.core/aio/core/functional/collections.py
- aio.core/aio/core/functional/generator.py
- aio.core/aio/core/subprocess/abstract/shell.py
- aio.core/aio/core/subprocess/async_subprocess.py
- aio.core/aio/core/subprocess/shell.py
- aio.core/tests/test_aio.py
- aio.core/tests/test_functional.py
- aio.core/tests/test_shell.py
> aio.core: Add `AwaitableGenerator`

- aio.core/tests/test_task.py
> aio.core.tasks: Add missing `concurrent` test

- aio.core/tests/test_dev.py
> aio.core.dev: Add missing test

- aio.core/aio/core/BUILD
- aio.core/aio/core/__init__.py
- aio.core/aio/core/event/__init__.py
- aio.core/aio/core/event/reactive.py
- aio.core/tests/test_event_reactive.py
> aio.core: Add event reactive types

- README.md
- aio.api.github/aio/api/github/BUILD
- aio.api.github/aio/api/github/abstract/api.py
- aio.api.github/aio/api/github/api.py
- aio.api.github/setup.cfg
- aio.api.github/tests/test_abstract_api.py
- aio.api.github/tests/test_api.py
- envoy.dependency.check/tests/test_integration_cves.py
> aio.api.github: Fix session handling and use aiohttp explicitly

- aio.run.checker/tests/test_checker.py
> aio.run.checker: Fix test

- deps/requirements.txt
- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/setup.cfg
- pants.toml
> Derive sha preload limit dynamically

- aio.core/aio/core/functional/utils.py
- aio.run.runner/aio/run/runner/runner.py
- aio.run.runner/tests/test_runner.py
https://github.com/bazelbuild/rules_python/issues/622
> Skip orjson and uvloop imports on macOS

- envoy.dependency.check/tests/BUILD
> envoy.dependency.check: Fix issue with missing test data

- envoy.code.check/envoy/code/check/abstract/base.py
- envoy.code.check/tests/test_abstract_base.py
> `envoy.code.check`: Make `ACodeCheck` `IReactive`

- envoy.code.check/envoy/code/check/abstract/checker.py
- envoy.code.check/tests/test_abstract_checker.py
> `envoy.code.check` Cleanup: Remove surplus check mark

- README.md
- aio.api.nist/aio/api/nist/abstract/downloader.py
- aio.api.nist/setup.cfg
- aio.api.nist/tests/test_abstract_downloader.py
- envoy.code.check/envoy/code/check/abstract/base.py
- envoy.code.check/setup.cfg
- envoy.dependency.check/envoy/dependency/check/abstract/release.py
- envoy.dependency.check/setup.cfg
- envoy.dependency.check/tests/test_abstract_release.py
> repo: Use `IExecutive` interface

- envoy.code.check/envoy/code/check/abstract/yapf.py
- envoy.code.check/envoy/code/check/typing.py
- envoy.code.check/tests/test_abstract_yapf.py
> `envoy.code.check`: Resolve Yapf blocking code issues

- .github/workflows/ci.yml
> repo: Temp disable typecheck

- envoy.code.check/envoy/code/check/abstract/checker.py
- envoy.code.check/envoy/code/check/abstract/flake8.py
- envoy.code.check/tests/test_abstract_checker.py
- envoy.code.check/tests/test_abstract_flake8.py
> `envoy.code.check`: Resolve blocking `flake8` issues

- aio.core/aio/core/functional/decorators.py
Currently co-routines can call an `async_property` concurrently, causing
it to load multiple times, event when its supposed to cache. This should fix it.
> `aio.core`: Load cached `async_property` co-operatively

- envoy.code.check/envoy/code/check/abstract/flake8.py
- envoy.code.check/tests/test_abstract_flake8.py
> `envoy.code.check`: Optimize `flake8` check

- aio.core/aio/core/directory/abstract/directory.py
- aio.core/aio/core/subprocess/abstract/shell.py
- aio.core/aio/core/subprocess/shell.py
- aio.core/tests/test_abstract_shell.py
- aio.core/tests/test_directory.py
- aio.core/tests/test_shell.py
> `aio.core`: Cleaups/optimizations for directory and shell

- envoy.dependency.check/envoy/dependency/check/abstract/release.py
- envoy.dependency.check/tests/test_abstract_release.py
> Space missing in sha check error message

- README.md
- aio.core/aio/core/BUILD
- aio.core/setup.cfg
> `aio.core`: Add `psutil` dep

- aio.core/aio/core/functional/utils.py
- aio.core/tests/test_functional.py
> `aio.core`: Add `min_batch_size` to `batched_jobs` util

- aio.core/aio/core/BUILD
- aio.core/aio/core/dev/__init__.py
- aio.core/aio/core/dev/debug.py
> `aio.core`: Add `debug.logging` decorator

- aio.core/aio/core/dev/debug.py
- aio.core/aio/core/event/executive.py
- aio.core/aio/core/functional/decorators.py
- aio.core/tests/test_directory.py
- aio.core/tests/test_event_executive.py
> `aio.core`: Improve debug logging

- aio.core/aio/core/event/executive.py
> `aio.core`: Handle partials in `execute` debug logging

- aio.core/aio/core/BUILD
- aio.core/aio/core/log/__init__.py
- aio.core/aio/core/log/logging.py
- aio.core/tests/test_log.py
> `aio.core`:  Add async queue logger

- aio.core/aio/core/functional/__init__.py
- aio.core/aio/core/functional/output.py
- aio.core/tests/test_functional.py
> `aio.core`: Remove unused `buffering` util

- envoy.code.check/envoy/code/check/abstract/checker.py
- envoy.code.check/tests/test_abstract_checker.py
> `envoy.code.check`: Optimize results reporting

- aio.core/aio/core/log/__init__.py
- aio.core/aio/core/log/logging.py
- envoy.gpg.identity/envoy/gpg/identity/identity.py
> `aio.core`: Remove `StoppableLogger`

- aio.core/aio/core/dev/debug.py
> `aio.core`: Add `trace` logging and improve debug output

- aio.core/aio/core/directory/__init__.py
- aio.core/aio/core/directory/abstract/directory.py
- aio.core/tests/test_directory.py
- aio.core/tests/test_log.py
> `aio.core`: Add missing tests

- aio.core/aio/core/directory/__init__.py
- aio.core/aio/core/directory/abstract/__init__.py
- aio.core/aio/core/directory/abstract/directory.py
- aio.core/aio/core/directory/directory.py
- aio.core/tests/test_directory.py
> `aio.core`: Cleanups and tests for directory utils

- README.md
- envoy.code.check/envoy/code/check/abstract/flake8.py
- envoy.code.check/envoy/code/check/abstract/glint.py
- envoy.code.check/envoy/code/check/abstract/shellcheck.py
- envoy.code.check/envoy/code/check/abstract/yapf.py
- envoy.code.check/setup.cfg
- envoy.code.check/tests/test_abstract_glint.py
- envoy.code.check/tests/test_abstract_shellcheck.py
- envoy.code.check/tests/test_abstract_yapf.py
> `envoy.code.check`: Cleanups and optimizations

- aio.core/aio/core/dev/debug.py
> `aio.core`: Fix for broken (untested) debug code

- aio.run.checker/aio/run/checker/decorators.py
- aio.run.checker/tests/test_decorators.py
> `aio.run.checker`: Fix preload decorator issue

- envoy.dependency.check/envoy/dependency/check/abstract/issues.py
- envoy.dependency.check/tests/test_abstract_issues.py
> Add proper filter for github-actions[bot] in ISSUES_SEARCH_TPL

- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/tests/test_abstract_checker.py
> Improve missing github token message in dep.checker

- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/tests/test_abstract_checker.py
> Remove psutil usage in checker

- .github/workflows/ci.yml
> repo: Use `./pants` to invoke pants in CI

- .github/workflows/ci.yml
> repo: Restrict CI to `main` branch

- .github/workflows/ci.yml
- .mypy.lock
- pants.toml
> repo: Update python -> 3.10

- .github/workflows/ci.yml
> repo: Add release to CI triggers

- .github/workflows/ci.yml
> repo: Fix and limit release CI trigger

- README.md
- aio.api.github/aio/api/github/BUILD
- aio.api.github/aio/api/github/__init__.py
- aio.api.github/aio/api/github/abstract/__init__.py
- aio.api.github/aio/api/github/abstract/api.py
- aio.api.github/aio/api/github/abstract/base.py
- aio.api.github/aio/api/github/abstract/commit.py
- aio.api.github/aio/api/github/abstract/issues/__init__.py
- aio.api.github/aio/api/github/abstract/issues/issues.py
- aio.api.github/aio/api/github/abstract/issues/tracker.py
- aio.api.github/aio/api/github/abstract/iterator.py
- aio.api.github/aio/api/github/abstract/label.py
- aio.api.github/aio/api/github/abstract/release.py
- aio.api.github/aio/api/github/abstract/repo.py
- aio.api.github/aio/api/github/abstract/tag.py
- aio.api.github/aio/api/github/interface.py
- aio.api.github/setup.cfg
- aio.api.github/tests/test_abstract_issues.py
- aio.api.github/tests/test_abstract_issues_tracker.py
- aio.api.github/tests/test_abstract_release.py
- aio.api.github/tests/test_interface.py
- envoy.dependency.check/envoy/dependency/check/abstract/dependency.py
- envoy.dependency.check/envoy/dependency/check/abstract/issues.py
- envoy.dependency.check/envoy/dependency/check/abstract/release.py
> `aio.api.github`: Add issue tracker interface

- DEVELOPER.md
> repo: Add DEVELOPER.md

- envoy.base.utils/envoy/base/utils/abstract/project/changelog.py
- envoy.base.utils/envoy/base/utils/exceptions.py
- envoy.base.utils/envoy/base/utils/utils.py
- envoy.base.utils/tests/test_abstract_project_changelogs.py
- envoy.base.utils/tests/test_utils.py
> `envoy.base.utils`: Improve error handling

- aio.core/aio/core/directory/abstract/directory.py
- aio.core/aio/core/functional/decorators.py
- aio.core/aio/core/stream/_reader.py
- aio.core/aio/core/tasks/tasks.py
> `aio.core`: Make use of the :walrus:

- README.md
- aio.api.github/aio/api/github/abstract/api.py
- aio.api.github/aio/api/github/abstract/issues/issues.py
- aio.api.github/aio/api/github/abstract/issues/tracker.py
- aio.api.github/setup.cfg
> `aio.api.github`: Make use of the :walrus:

- README.md
- aio.api.nist/aio/api/nist/abstract/cpe.py
- aio.api.nist/aio/api/nist/abstract/cve.py
- aio.api.nist/setup.cfg
> `aio.api.nist`: Make use of the :walrus:

- aio.run.checker/aio/run/checker/checker.py
- aio.run.checker/setup.cfg
> `aio.run.checker`: Make use of the :walrus:

- envoy.base.utils/envoy/base/utils/abstract/project/changelog.py
- envoy.base.utils/envoy/base/utils/abstract/project/inventory.py
> `envoy.base.utils`: Make use of the :walrus:

- envoy.code.check/envoy/code/check/abstract/changelog.py
- envoy.code.check/envoy/code/check/abstract/checker.py
- envoy.code.check/envoy/code/check/abstract/shellcheck.py
- envoy.code.check/envoy/code/check/abstract/yapf.py
> `envoy.code.check`: Make use of the :walrus:

- pytest-abstracts/pytest_abstracts/__init__.py
- pytest-abstracts/tests/test_abstracts.py
> `pytest-abstracts`: Add implementation

- pytest-abstracts/pytest_abstracts/__init__.py
> `pytest-abstracts`: Improve `iface` checks

- envoy.base.utils/envoy/base/utils/jinja_env_cmd.py
> `envoy.base.utils`: Minor typing cleanup

- envoy.code.check/envoy/code/check/typing.py
Signed-off-by: Kuat Yessenov <kuat@google.com>
> add type_urls to extension schema

- .github/workflows/ci.yml
this command achieves the same as the previous one and I think it is simpler
> Simplify typecheck (mypy) step in CI

- envoy.code.check/envoy/code/check/abstract/base.py
- envoy.code.check/envoy/code/check/abstract/changelog.py
- envoy.code.check/envoy/code/check/abstract/checker.py
- envoy.code.check/envoy/code/check/abstract/extensions.py
- envoy.code.check/envoy/code/check/abstract/flake8.py
- envoy.code.check/envoy/code/check/abstract/glint.py
- envoy.code.check/envoy/code/check/abstract/runtime_guards.py
- envoy.code.check/envoy/code/check/abstract/shellcheck.py
- envoy.code.check/envoy/code/check/abstract/yapf.py
- envoy.code.check/envoy/code/check/checker.py
- envoy.code.check/envoy/code/check/interface.py
- envoy.code.check/tests/test_checker.py
> `envoy.code.check`: Improve interfaces/namespacing

- envoy.distribution.distrotest/envoy/distribution/distrotest/distrotest.py
> `envoy.distribution.distrotest`: Minor fix for docker image handling

- README.md
- deps/requirements.txt
- envoy.code.check/setup.cfg
> `envoy.code.check`: Bump e.b.utils dep for changelog fix

- .github/workflows/ci.yml
> repo: Pin python to 3.9 for pants

- aio.api.github/aio/api/github/abstract/release.py
- envoy.dependency.check/envoy/dependency/check/abstract/issues.py
- envoy.dependency.check/envoy/dependency/check/abstract/release.py
> repo: Remove `version.LegacyVersion`

- .github/workflows/ci.yml
> repo: Fix pants in CI

- .github/workflows/ci.yml
> repo: Remove python env

- .gitignore
- envoy.docs.sphinx_runner/envoy/docs/sphinx_runner/sphinx_rtd_theme/BUILD
- envoy.docs.sphinx_runner/envoy/docs/sphinx_runner/sphinx_rtd_theme/locale/sphinx.pot
- envoy.docs.sphinx_runner/setup.cfg
> `envoy.docs.sphinx_runner`: Fix `rtd_theme` localization files in build

- .mypy.lock
> repo: Bump mypy version -> 1.0.0

- .pytest.lock
- pants.toml
> repo: Bump pytest -> 7.2.1

- envoy.base.utils/setup.cfg
- envoy.dependency.check/envoy/dependency/check/BUILD
- envoy.docs.sphinx_runner/envoy/docs/sphinx_runner/BUILD
> repo: Add missing explicit deps

- .mypy.lock
- aio.api.nist/aio/api/nist/abstract/cve.py
- aio.run.runner/aio/run/runner/runner.py
- envoy.base.utils/envoy/base/utils/data_env.py
- envoy.base.utils/envoy/base/utils/jinja_env.py
- envoy.dependency.check/envoy/dependency/check/abstract/checker.py
- envoy.dependency.check/tests/test_abstract_checker.py
- envoy.distribution.release/envoy/distribution/release/commands.py
- envoy.distribution.release/tests/test_commands.py
- pants.toml
> repo: Bump mypy -> .981 (correctly!)

- README.md
- deps/requirements.txt
- envoy.code.check/envoy/code/check/abstract/flake8.py
- envoy.code.check/setup.cfg
- envoy.code.check/tests/test_abstract_flake8.py
> `envoy.code.check`: Make compatible with flake8 > 6

- .github/workflows/ci.yml
> ci: Turn the lights on

- gh-actions/docker/cache/prime/action.yml
- gh-actions/docker/cache/restore/action.yml
- gh-actions/docker/fetch/action.yml
- gh-actions/docker/shas/action.yml
- gh-actions/foreach/action.yml
- gh-actions/github/check/start/action.yml
- gh-actions/github/check/update/action.yml
- gh-actions/github/checkout/action.yml
- gh-actions/github/context/action.yml
- gh-actions/github/env/load/action.yml
- gh-actions/github/env/save/action.yml
- gh-actions/github/env/save/action.yml~
- gh-actions/github/env/summary/action.yml
- gh-actions/github/env/title/action.yml
- gh-actions/github/merge-commit/action.yml
- gh-actions/github/pr/action.yml
- gh-actions/github/run/action.yml
- gh-actions/json/table/action.yml
- gh-actions/str/desanitize/action.yml
- gh-actions/str/sanitize/action.yml
- gh-actions/using/recurse/action.yml
- gh-actions/using/steps/action.yml
and improve token handling in checks/start
> gh-actions: Improve debugging

- gh-actions/github/env/summary/action.yml
this approach was obsoleted by the addition of context vars
> `gh-actions/github/env/summary`: Remove unneeded sanitization

- gh-actions/github/check/update/action.yml
> `gh-actions/github/check/update`: Fix uri handling of check name

- .github/workflows/actions.yml
> use working-directory instead of cd command

- gh-actions/appauth/package-lock.json
- gh-actions/appauth/package.json
- gh-actions/dispatch/package-lock.json
- gh-actions/dispatch/package.json
- gh-actions/github/checks/package-lock.json
- gh-actions/github/checks/package.json
- gh-actions/github/mutex/package-lock.json
- gh-actions/github/mutex/package.json
- gh-actions/jq/package-lock.json
- gh-actions/jq/package.json
- gh-actions/retest/package-lock.json
- gh-actions/retest/package.json
- gh-actions/torun/package-lock.json
- gh-actions/torun/package.json
> unify actions naming logic

- README.md
- templates/README.header.md.tmpl
> Provide OpenSSF Scorecard in README.md

- .github/workflows/codeql.yml
- .github/workflows/scorecard.yml
> ci/creds: Add restriction and allow scorecard admin access

- gh-actions/bson/action.yml
- gh-actions/cache/prime/action.yml
- gh-actions/cache/restore/action.yml
- gh-actions/docker/cache/prime/action.yml
- gh-actions/docker/cache/restore/action.yml
- gh-actions/docker/fetch/action.yml
- gh-actions/docker/shas/action.yml
- gh-actions/envoy/ci/request/action.yml
- gh-actions/envoy/run/summary/action.yml
- gh-actions/foreach/action.yml
- gh-actions/github/artifact/download/action.yml
- gh-actions/github/checkout/action.yml
- gh-actions/github/command/action.yml
- gh-actions/github/merge-commit/action.yml
- gh-actions/github/mutex/README.md
- gh-actions/github/pr/action.yml
- gh-actions/github/run/action.yml
- gh-actions/json/table/action.yml
- gh-actions/upload/diff/action.yml
- gh-actions/using/recurse/action.yml
> pin actions versions

- README.md
- templates/README.header.md.tmpl
> update OSSF Scorecard badge link

- aio.api.bazel/aio/api/bazel/abstract/base.py
- aio.api.bazel/aio/api/bazel/interface.py
- aio.api.github/aio/api/github/abstract/actions/actions.py
- aio.api.github/aio/api/github/abstract/issues/issues.py
- aio.api.github/aio/api/github/abstract/repo.py
- aio.api.github/aio/api/github/interface.py
- aio.core/aio/core/functional/generator.py
- aio.core/aio/core/pipe/abstract/pipe.py
- aio.core/aio/core/utils/data.py
- aio.run.checker/aio/run/checker/decorators.py
- envoy.base.utils/envoy/base/utils/utils.py
- envoy.code.check/envoy/code/check/abstract/extensions.py
- pytest-iters/pytest_iters/__init__.py
this fixes half of the problems created by updating mypy, and should be harmless
> mypy: Make `Optional` compulsory

- .mypy.lock
- aio.api.github/aio/api/github/api.py
- aio.api.nist/aio/api/nist/nist.py
- aio.core/aio/core/dev/debug.py
- aio.core/aio/core/directory/directory.py
- aio.run.checker/aio/run/checker/checker.py
- deps/requirements.txt
- envoy.code.check/envoy/code/check/checker.py
- envoy.dependency.check/envoy/dependency/check/checker.py
- envoy.distribution.release/envoy/distribution/release/commands.py
- envoy.distribution.release/envoy/distribution/release/runner.py
- envoy.distribution.repo/envoy/distribution/repo/deb.py
- envoy.distribution.repo/envoy/distribution/repo/runner.py
- envoy.github.release/envoy/github/release/assets.py
- pants.toml
- update mypy
- remove unnecessary/update implementation declarations
- improving typing on code debugger
> python: Update mypy (+typing cleanups)

- envoy.docs.sphinx_runner/envoy/docs/sphinx_runner/ext/validating_code_block.py
see https://github.com/python/typeshed/pull/11550
> `envoy.docs.sphinx_runner`: Workaround broken sphinx typing

- gh-actions/docker/cache/prime/action.yml
> gh-actions/docker/cache: Add key suffix

- gh-actions/envoy/ci/request/action.yml
This reverts commit 27c083bdb5bc272ac8a23ceea6719656b2db52ca.
> Revert "gh-actions/envoy/ci: Add arm64 support (#2137)"

- bazel/versions.bzl
> bazel: Release 0.3.0

- bazel/compile/libtool.bzl
- bazel/versions.bzl
> bazel: Release 0.3.4

- gh-actions/gcp/setup/requirements.in
- gh-actions/gcp/setup/requirements.txt
Reverts envoyproxy/toolshed#2729
> Revert "build(deps): bump pyopenssl from 24.2.1 to 25.1.0 in /gh-actions/gcp/setup"
